---
output: github_document
---

### Chad Allison

Durham, NC | chadrallison@outlook.com | (304) 546-6493 | [LinkedIn](https://www.linkedin.com/in/chad-allison-8808a31a0/){target="_blank"} | [GitHub](https://github.com/chadallison){target="_blank"} | [RPubs](https://rpubs.com/chadallison){target="_blank"}

___

### **Education**

**University of North Carolina at Chapel Hill**: *Graduated May 2022 with Highest Distinction*

- Bachelor of Science in Statistics and Analytics, American Studies minor
- GPA: 3.87
- Honors: Dean's List all eligible semesters
- Activities: Club Golf Treasurer; "Swim Across Carolina" Program Winner

___

### **Experience**

##### **IBM**

**Data Scientist - Conversion Analytics**: *May 2023 - Present*

- Working on "Defining Demos" team with focus on customer conversions from demo videos on IBM pages
- Assisting with building dashboards using data from disparate sources to provide insight to marketing decision-makers
- Querying from highly granular data sources and finding most efficient and informative ways to summarize information

**Data Scientist - Client Engineering**: *June 2022 - May 2023*

- Co-creating projects with clients using data science and programming skills
- Working with cutting-edge IBM technologies such as Watson along with other open-source libraries and frameworks
- Client projects include building machine learning models such as neural networks for image classification and clustering algorithms for customer segmentation

___

##### **UNC Baseball**

**Data Analyst**: *December 2020 - June 2022*

- Deliver analyses to coaches and players to improve team performance and prepare for opponents
- Utilize programming skills in R to explore data and extract useful information
- Assist in maintaining team RShiny websites

___

##### **Fleet Feet**

**Digital Analyst Intern**: *May 2021 - August 2021*

- Collected, organized, and joined data from various sources
- Utilized Google's CausalImpact R package to evaluate marketing campaigns and advertising initiatives
- Collaborated with digital marketing teams to inform efficient advertising expenditure

___

##### **Projects**

- **[MLB CPR](https://github.com/chadallison/mlb_cpr){target="_blank"} & [MLB Scorigami](https://rpubs.com/chadallison/mlb_scorigami){target="_blank"}**: Visualizations of Team Performance Metrics for MLB Baseball | *March 2023 - Present*
- **[Stanford University WiDS Datathon](https://github.com/chadallison/wids_datathon_2023){target="_blank"} (Climate Change)** | *February 2023*
- **[abnoRmal](https://github.com/chadallison/abnoRmal){target="_blank"} & [Ode to the Strokes](https://rpubs.com/chadallison/ode_strokes){target="_blank"}**: Exploratory Analysis of Music | *January/February 2023*
- **[Advent of Code](https://github.com/chadallison/advent_of_code_2022){target="_blank"} & [Project Euler](https://github.com/chadallison/project_euler){target="_blank"}**: Math and Programming Challenges | *December 2022 - Present*
- **Analysis and Modeling of [NFL](https://github.com/chadallison/nfl_modeling){target="_blank"} and [College Basketball](https://github.com/chadallison/hoopR){target="_blank"} Play-by-Play Data** | *January/February 2023*
- **NC State Datathon** (Raleigh NIBRS Police Data) | *March 2021*
- **Alcohol Consumption v. Academic Performance** (University Data Science Project) | *November 2020*

### **Skills**

- Languages: R, SQL, Python -- Data cleaning, visualizing, manipulating, machine learning, database querying, APIs
- Experienced in RStudio, RMarkdown; Tableau; Microsoft Office; Google Analytics; Amazon S3; GitHub
- Communicating analyses to technical and non-technical audiences
- Eagerness to learn new skills and ways of thinking

___































